"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
export default function Admin(){
  const [d,setD]=useState<any>(null),[msg,setMsg]=useState("");
  async function load(){const r=await fetch("/api/admin/overview",{cache:"no-store",headers:{"cache-control":"no-cache"}});if(r.status===403){setMsg("Admin access required.");return}setD(await r.json())}
  useEffect(()=>{load()},[]);
  async function toggle(id:string,enabled:boolean){await fetch("/api/admin/sources",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,enabled})});load()}
  async function remove(id:string){await fetch("/api/admin/jobs/"+id,{method:"DELETE"});load()}
  return <main className="container section"><nav><Link href="/">← RolePilot</Link></nav><p className="eyebrow">Control plane</p><h1>RolePilot Admin</h1>{msg&&!d?<div className="empty"><p>{msg}</p><Link className="btn" href="/auth?next=/admin" style={{marginTop:12,display:"inline-flex"}}>Sign in to Admin</Link></div>:!d?<p>Loading health…</p>:<>
    <div className="grid"><div className="card"><div className="eyebrow">Active jobs</div><h2>{d.jobs}</h2></div><div className="card"><div className="eyebrow">Companies</div><h2>{d.companies}</h2></div><div className="card"><div className="eyebrow">AI coverage</div><h2>{d.jobs?Math.round(d.aiJobs/d.jobs*100):0}%</h2><p>{d.aiConfigured?"AI credential configured":"Add HF_TOKEN or OPENAI_API_KEY"}</p></div><div className="card"><div className="eyebrow">Monetization</div><p>GA: {d.analyticsValid?"valid":"missing/invalid"} · AdSense: {d.adsenseValid?"valid":"missing/invalid"}</p></div></div>
    <section className="card"><p className="eyebrow">First-party analytics</p><h2>Web traffic</h2><p>Anonymous pageviews and product events captured in RolePilot.</p><div className="grid"><div className="card soft"><div className="eyebrow">Events · 24h</div><h2>{d.analytics24}</h2></div><div className="card soft"><div className="eyebrow">Events · 7d</div><h2>{d.analytics7}</h2></div><div className="card soft"><div className="eyebrow">Sessions · 7d</div><h2>{d.sessions7}</h2></div></div><div className="grid" style={{marginTop:16}}>
      <div className="card soft"><div className="eyebrow">Job views · 7d</div><h2>{d.analytics?.jobViews7??d.analytics7}</h2></div>
      <div className="card soft"><div className="eyebrow">Apply clicks · 7d</div><h2>{d.analytics?.applyClicks7??0}</h2></div>
      <div className="card soft"><div className="eyebrow">Job → apply</div><h2>{(d.analytics?.jobToApplyRate??0)+"%"}</h2></div>
      <div className="card soft"><div className="eyebrow">Searches · 7d</div><h2>{d.analytics?.searches7??0}</h2></div>
      <div className="card soft"><div className="eyebrow">Resume uploads</div><h2>{d.analytics?.resumeUploads7??0}</h2></div>
      <div className="card soft"><div className="eyebrow">Resume match views</div><h2>{d.analytics?.resumeMatches7??0}</h2></div>
      <div className="card soft"><div className="eyebrow">Saves</div><h2>{d.analytics?.saves7??0}</h2></div>
      <div className="card soft"><div className="eyebrow">Auth success</div><h2>{d.analytics?.authSuccess7??0}</h2></div>
    </div><div className="grid" style={{marginTop:16}}><div className="card"><h3>Top pages · 7d</h3><ul>{(d.topPages||[]).map((p:any)=><li key={p.path}>{p.path||"/"} · {p.count}</li>)}</ul></div><div className="card"><h3>Top searches · 7d</h3><ul>{(d.analytics?.topQueries||[]).map((e:any)=><li key={e.query}>{e.query} · {e.count}</li>)}</ul></div><div className="card"><h3>Traffic sources · 7d</h3><ul>{(d.analytics?.trafficSources||[]).map((e:any)=><li key={e.source}>{e.source} · {e.count}</li>)}</ul></div><div className="card"><h3>Devices · 7d</h3><ul>{(d.analytics?.devices||[]).map((e:any)=><li key={e.device}>{e.device} · {e.count}</li>)}</ul></div><div className="card"><h3>Events · 7d</h3><ul>{(d.eventCounts||[]).map((e:any)=><li key={e.event_name}>{e.event_name} · {e.count}</li>)}</ul></div></div></section>
    <section className="card"><h2>Source health</h2><div className="grid">{d.sourceRows.map((s:any)=><article className="card" key={s.id}><h3>{s.name}</h3><p>{s.kind} · {s.last_count||0} jobs</p><p className="score">{s.last_error||("Last success: "+(s.last_success_at||"never"))}</p><button className="chip" onClick={()=>toggle(s.id,!s.enabled)}>{s.enabled?"Disable":"Enable"}</button></article>)}</div></section>
    <section className="card"><h2>Recent job moderation</h2><div className="grid">{d.recentJobs.map((j:any)=><article className="card" key={j.id}><h3 className="title"><Link href={"/jobs/"+j.slug}>{j.title}</Link></h3><p>{j.company_name} · {j.source_name}</p><p className="score">{j.status} · {j.ai_summary?"AI enriched":"No AI summary"}</p>{j.status==="active"&&<button className="chip" onClick={()=>remove(j.id)}>Reject listing</button>}</article>)}</div></section>
    <section className="card"><h2>Ingestion history</h2><ul>{d.runs.map((r:any)=><li key={r.id}>{new Date(r.started_at).toLocaleString()} · {r.status} · {r.jobs_upserted} published · {r.sources_succeeded}/{r.sources_total} sources OK</li>)}</ul></section>
  </>}</main>
}