import Link from "next/link";
import LiveInventory from "./components/live-inventory";
export const dynamic="force-static";
export const revalidate=3600;

export default function Home(){
  return <><header className="nav"><div className="container navin"><Link href="/" className="brand">Job<span>News</span></Link><nav className="links"><Link href="/jobs">Jobs</Link><Link href="/companies">Companies</Link><Link href="/skills">Skills</Link><Link href="/locations">Locations</Link><Link href="/jobs?type=internship">Internships</Link><Link href="/jobs?mode=remote">Remote</Link><Link href="/account">Account</Link></nav><Link className="chip" href="/jobs">Explore all</Link></div></header>
<main><section className="hero"><div className="container"><div className="eyebrow">AI-assisted opportunity discovery</div><h1>Every useful job lead, organized before you apply.</h1><p>Fresh jobs, internships and remote roles from public feeds and direct career systems, deduplicated, freshness-checked and linked to the original application.</p><form className="search" action="/jobs"><input className="input" name="q" placeholder="Search Python, AI engineer, internship, Pune…"/><select className="select" name="mode" defaultValue=""><option value="">Any work mode</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select><button className="btn">Smart search</button></form><div className="tabs"><Link className="chip active" href="/jobs">All</Link><Link className="chip" href="/jobs?fresh=today">New today</Link><Link className="chip" href="/jobs?type=internship">Internships</Link><Link className="chip" href="/jobs?mode=remote">Remote</Link><Link className="chip" href="/companies">Companies</Link><Link className="chip" href="/skills">Skills</Link></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">Live inventory</div><h2>Current opportunities</h2><LiveInventory/><div className="grid" style={{marginTop:20}}><article className="card"><div className="eyebrow">Search</div><h3>Find roles by intent, skill or company.</h3><p>Use semantic search to discover relevant opportunities without relying on exact job-title wording.</p><Link className="chip" href="/jobs">Browse jobs →</Link></article><article className="card"><div className="eyebrow">Matching</div><h3>Profile → semantic matches</h3><p>Save roles, track application stages and use your profile to surface relevant openings.</p><Link className="chip" href="/account">Open your cockpit →</Link></article><article className="card"><div className="eyebrow">Sources</div><h3>36 public sources monitored.</h3><p>Listings are source-linked, freshness-checked and refreshed twice daily.</p><Link className="chip" href="/about">Methodology →</Link></article></div></div></section></main><footer className="footer"><div className="container">© 2026 JobNews · <Link href="/privacy">Privacy</Link> · <Link href="/disclaimer">Disclaimer</Link> · <Link href="/about">Methodology</Link></div></footer></>
}
