import Link from "next/link";
import Brand from "./components/brand";
import LiveInventory from "./components/live-inventory";
import ResumeUpload from "./components/resume-upload";
export const dynamic="force-static";
export const revalidate=3600;

export default function Home(){
  return <><header className="nav"><div className="container navin"><Brand/><nav className="links"><Link href="/jobs">Explore</Link><Link href="/india">🇮🇳 India</Link><Link href="/internships">Internships</Link><Link href="/remote-jobs">Remote</Link><Link href="/companies">Companies</Link><Link href="/skills">Skills</Link><Link href="/locations">Locations</Link><Link href="/account">Your Radar</Link></nav><a className="chip active" href="#resume">Upload resume</a></div></header>
  <main>
    <section className="hero"><div className="container hero-grid"><div><div className="eyebrow"><span className="pulse"><i/> Radar live</span></div><h1>Find the right role. Before the crowd.</h1><p>Upload your resume once. RolePilot continuously discovers fresh opportunities, filters the noise, explains why they fit and sends you to the original employer or ATS application.</p><form className="search" action="/jobs"><input className="input" name="q" placeholder="Try: remote Python internships in India"/><select className="select" name="mode" defaultValue=""><option value="">Any work mode</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select><button className="btn">Search opportunities</button></form><div className="chips"><a className="chip active" href="#resume">Upload resume</a><Link className="chip" href="/jobs?fresh=today">Fresh today</Link><Link className="chip" href="/jobs?mode=remote">Remote</Link><Link className="chip" href="/jobs?type=internship">Internships</Link></div></div><div className="radar-panel"><div className="eyebrow">Market pulse</div><div style={{marginTop:12}}><LiveInventory/></div><div className="reason" style={{marginTop:16}}><b>Signal, not noise.</b><br/>The large inventory stays behind the scenes. Your radar surfaces the opportunities worth your attention.</div></div></div></section>
    <section id="resume" className="section"><div className="container"><ResumeUpload/></div></section>
    <section className="section"><div className="container"><div className="eyebrow">How RolePilot works</div><h2>Discover → Match → Apply</h2><div className="grid"><article className="card"><div className="eyebrow">01 · Discover</div><h3>Fresh opportunities</h3><p>Supported employer and ATS sources are monitored repeatedly so newly discovered roles can enter the index without waiting for a manual upload.</p></article><article className="card"><div className="eyebrow">02 · Match</div><h3>Your profile first</h3><p>We combine resume signals, skills, role intent, preferences and semantic relevance instead of relying on a single keyword search.</p></article><article className="card"><div className="eyebrow">03 · Apply</div><h3>Go to the source</h3><p>RolePilot is the discovery layer. The application link takes you to the employer or employer ATS whenever the source supports it.</p></article></div></div></section>
  </main>
  <footer className="footer"><div className="container">© 2026 RolePilot · AI-powered job discovery & matching · <Link href="/privacy">Privacy</Link> · <Link href="/disclaimer">Disclaimer</Link> · <Link href="/about">Methodology</Link></div></footer></>
}