import fs from "node:fs";import path from "node:path";import {getDb} from "./db";
export type Job={id:string;slug:string;title:string;company:string;description:string;location:string;workMode:"remote"|"hybrid"|"onsite"|"unknown";type:"full-time"|"part-time"|"contract"|"internship"|"fellowship"|"other";salary:string;salaryMin?:number;salaryMax?:number;currency?:string;skills:string[];category:string;experience:string;publishedAt:string;updatedAt:string;sourceName:string;sourceUrl:string;applyUrl:string;verified:boolean;freshness:"today"|"this-week"|"older";tags:string[];aiSummary?:string;aiHighlights?:string[];companyId?:string;status?:string};
const file=path.join(process.cwd(),"data","jobs.json");
export function slugify(v:string){return v.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,82)}
function normalize(j:any):Job{return {...j,id:String(j.id||""),title:typeof j.title==="string"&&j.title.trim()?j.title:"Untitled opportunity",slug:typeof j.slug==="string"&&j.slug.trim()?j.slug:slugify(String(j.title||"opportunity")),company:typeof j.company==="string"&&j.company.trim()?j.company:"Unknown company",description:typeof j.description==="string"?j.description:"",location:typeof j.location==="string"&&j.location.trim()?j.location:"Location not specified",workMode:["remote","hybrid","onsite","unknown"].includes(j.workMode)?j.workMode:"unknown",type:["full-time","part-time","contract","internship","fellowship","other"].includes(j.type)?j.type:"other",salary:typeof j.salary==="string"?j.salary:"Not disclosed",salaryMin:typeof j.salaryMin==="number"?j.salaryMin:undefined,salaryMax:typeof j.salaryMax==="number"?j.salaryMax:undefined,currency:typeof j.currency==="string"?j.currency:undefined,skills:Array.isArray(j.skills)?j.skills.map(String).filter(Boolean):[],category:typeof j.category==="string"&&j.category.trim()?j.category:"Other",experience:typeof j.experience==="string"?j.experience:"Not specified",publishedAt:typeof j.publishedAt==="string"?j.publishedAt:"",updatedAt:typeof j.updatedAt==="string"?j.updatedAt:"",sourceName:typeof j.sourceName==="string"?j.sourceName:"Unknown source",sourceUrl:typeof j.sourceUrl==="string"?j.sourceUrl:"",applyUrl:typeof j.applyUrl==="string"?j.applyUrl:j.sourceUrl||"",verified:Boolean(j.verified),freshness:["today","this-week","older"].includes(j.freshness)?j.freshness:"older",tags:Array.isArray(j.tags)?j.tags.map(String).filter(Boolean):[],aiSummary:typeof j.aiSummary==="string"?j.aiSummary:undefined,aiHighlights:Array.isArray(j.aiHighlights)?j.aiHighlights.map(String).filter(Boolean):[],companyId:typeof j.companyId==="string"?j.companyId:undefined,status:typeof j.status==="string"?j.status:"active"}}
export function getJobs():Job[]{try{const x=JSON.parse(fs.readFileSync(file,"utf8"));return Array.isArray(x)?x.map(normalize):[]}catch{return[]}}
export function getActiveJobs(){return getJobs().filter(j=>j.status!=="rejected"&&Date.parse(j.publishedAt||j.updatedAt)>=Date.now()-60*24*60*60*1000).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt))}
function row(r:any){return normalize({id:r.id,slug:r.slug,title:r.title,company:r.company_name,description:r.description,location:r.location,workMode:r.work_mode,type:r.employment_type,salary:r.salary_text,salaryMin:r.salary_min,salaryMax:r.salary_max,currency:r.currency,skills:r.skills,category:r.category,experience:r.experience,publishedAt:r.published_at,updatedAt:r.updated_at,sourceName:r.source_name,sourceUrl:r.source_url,applyUrl:r.apply_url,verified:r.verified,freshness:r.freshness,tags:r.tags,aiSummary:r.ai_summary,aiHighlights:r.ai_highlights,companyId:r.company_id,status:r.status})}
export async function getActiveJobsAsync(){const sql=getDb();if(!sql)return getActiveJobs();try{const data=await sql.query("SELECT * FROM public.jobs WHERE status='active' AND coalesce(published_at,updated_at)>=now()-interval '60 days' ORDER BY published_at DESC NULLS LAST LIMIT 5000",[]);return data.length?data.map(row):getActiveJobs()}catch{return getActiveJobs()}}
export async function getJobAsync(slug:string){const sql=getDb();if(!sql)return getJobs().find(j=>j.slug===slug);try{const data=await sql.query("SELECT * FROM public.jobs WHERE slug=$1 AND status='active' LIMIT 1",[slug]);return data[0]?row(data[0]):getJobs().find(j=>j.slug===slug)}catch{return getJobs().find(j=>j.slug===slug)}}
export function getJob(slug:string){return getActiveJobs().find(j=>j.slug===slug)}
export function titleFor(j:Job){return j.title+" at "+j.company+" — JobNews"}export function descFor(j:Job){return "Find "+[j.title,"at "+j.company,j.location,j.type,j.salary,j.skills.slice(0,5).join(", ")].filter(Boolean).join(" · ")+". View source details and apply directly through the original employer or job source."}export function companySlug(name:string){return slugify(name)}