import fs from "node:fs/promises";import crypto from "node:crypto";import {neon} from "@neondatabase/serverless";
const baseSources=JSON.parse(await fs.readFile("data/sources.json","utf8")),atsSources=JSON.parse(await fs.readFile("data/ats-sources.json","utf8").catch(()=>"[ ]")),now=new Date().toISOString(),OUT="data/jobs.json",db=process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null;
const decode=(s="")=>{let out=String(s??"");for(let i=0;i<3;i++){const next=out.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#x2F;|&#47;/gi,"/").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)));if(next===out)break;out=next}return out};
const strip=(s="")=>decode(s).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const companyFromBoard=(board="")=>({airtable:"Airtable",asana:"Asana",cloudflare:"Cloudflare",datadog:"Datadog",discord:"Discord",figma:"Figma",gitlab:"GitLab",hubspot:"HubSpot",intercom:"Intercom",reddit:"Reddit",scaleai:"Scale AI",stripe:"Stripe",twilio:"Twilio",webflow:"Webflow",mongodb:"MongoDB",duolingo:"Duolingo",toast:"Toast"}[String(board).toLowerCase()]||String(board).replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()));
const slug=s=>String(s).toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90),hash=s=>crypto.createHash("sha1").update(s).digest("hex").slice(0,14);
const value=(x,...keys)=>{for(const k of keys){if(x?.[k]!==undefined&&x?.[k]!==null&&x?.[k]!=="")return x[k]}};
function canonicalUrl(raw=""){try{const u=new URL(String(raw));u.hash="";const host=u.hostname.toLowerCase().replace(/^www\./,"");if(host==="boards.greenhouse.io"||host==="job-boards.greenhouse.io"||host==="boards-api.greenhouse.io")u.hostname="boards.greenhouse.io";for(const k of [...u.searchParams.keys()]){if(/^utm_/i.test(k)||/^(source|ref|referrer|gh_jid)$/i.test(k))u.searchParams.delete(k)}u.pathname=u.pathname.replace(/\/+$/,"");u.search=u.searchParams.toString()?"?"+u.searchParams.toString():"";return u.toString()}catch{return String(raw||"").trim()}}
function stableFingerprint(j){const apply=canonicalUrl(j?.applyUrl||j?.sourceUrl||"");if(apply)return hash("apply:"+apply);return hash([String(j?.title||"").toLowerCase().trim(),String(j?.company||"").toLowerCase().trim(),String(j?.location||"").toLowerCase().trim()].join("|"))}
function knownCompany(name=""){return Boolean(String(name).trim())&&!/^(unknown company|unknown|n\/?a|not disclosed)$/i.test(String(name).trim())}
function quality(j){const company=knownCompany(j?.company)?80:0;const desc=Math.min(30,String(j?.description||"").length/600);const category=j?.category&&j.category!=="Other"?8:0;const source=/^(greenhouse|lever|ashby)$/i.test(String(j?.sourceKind||""))?20:0;return company+desc+category+source}
function jobIdentityKey(j){const apply=canonicalUrl(j?.applyUrl||j?.sourceUrl||"");return apply?"apply:"+apply:"fallback:"+stableFingerprint(j)}
function dedupeJobs(input){const map=new Map();for(const item of input){const key=jobIdentityKey(item),prev=map.get(key);if(!prev){map.set(key,item);continue}const itemScore=quality(item),prevScore=quality(prev),winner=itemScore>prevScore?item:prev;const stableId=winner.id||prev.id||item.id;map.set(key,{...winner,id:stableId,fingerprint:stableFingerprint(winner)})}return [...map.values()]}
function inferType(t){if(/intern|internship|graduate intern/i.test(t))return"internship";if(/fellow/i.test(t))return"fellowship";if(/contract/i.test(t))return"contract";if(/part[- ]time/i.test(t))return"part-time";if(/full[- ]time/i.test(t))return"full-time";return"other"}\nfunction inferExperience(title,desc,explicit=""){const raw=String(explicit||"").trim();const s=String(title||"")+" "+String(desc||"")+" "+raw;if(/not (for|open to).{0,30}(fresh|graduate|entry)/i.test(s))return raw||"Not specified";if(/intern|internship|graduate (?:engineer|software|developer|trainee)|trainee|apprentice|new grad|new graduate|fresher|entry[- ]level|campus hiring|early career|recent graduates?|0\\s*(?:-|–|to)\\s*2|0\\s*[-–]\\s*1\\s*year|0\\s*years?/i.test(s))return"fresher";if(/1\s*(?:-|–|to)\s*2\s*years?|1\s*[-–]\s*3\s*years?/i.test(s))return"0-3";if(/2\s*(?:-|–|to)\s*4\s*years?|3\s*(?:-|–|to)\s*5\s*years?/i.test(s))return"3-5";return raw||"Not specified"}\nconst INDIA_LOCATION=/india|bengaluru|bangalore|hyderabad|pune|mumbai|delhi|gurgaon|gurugram|noida|new delhi|chennai|kolkata|ahmedabad|jaipur|kochi|indore|nagpur/i;\nconst TECH_ROLE=/software|developer|engineering|engineer|programmer|frontend|backend|full[- ]?stack|mobile|android|ios|flutter|react|node|python|java|javascript|typescript|data|analytics|ai|machine learning|ml|llm|cloud|devops|sre|platform|kubernetes|aws|azure|gcp|cyber|security|soc|qa|test automation|product design|ux|ui|technical support|implementation/i;\nfunction isIndiaJob(j){return INDIA_LOCATION.test([j.location,j.company,j.sourceUrl,j.applyUrl].join(" "))}\nfunction isTechJob(j){return TECH_ROLE.test([j.title,j.category,(j.skills||[]).join(" "),j.description].join(" "))}\nfunction retainOpportunity(j){const india=isIndiaJob(j);const tech=isTechJob(j);return india||tech}
function inferMode(location,title,desc=""){const s=(location+" "+title+" "+desc).toLowerCase();if(/remote|work from home|distributed|worldwide/.test(s))return"remote";if(/hybrid/.test(s))return"hybrid";if(/on[- ]site|onsite|in office/.test(s))return"onsite";return"unknown"}
function dateOrNow(v){
  const min=Date.parse("1990-01-01T00:00:00.000Z"),max=Date.now()+5*365*24*60*60*1000;
  try{
    if(v===undefined||v===null||String(v).trim()==="")return now;
    const raw=String(v).trim();
    const numeric=/^-?\d+(?:\.\d+)?$/.test(raw)?Number(raw):null;
    let d;
    if(numeric!==null){
      const n=Math.abs(numeric);
      d=new Date(n>1e12?numeric:n*1000);
    }else{
      d=new Date(v);
    }
    const t=d.getTime();
    return Number.isFinite(t)&&t>=min&&t<=max?d.toISOString():now;
  }catch{return now}
}
function common(x,sourceName,sourceKind){const description=strip(value(x,"description","jobDescription","content","excerpt")||""),title=String(value(x,"title","jobTitle")||"Opportunity"),company=String(value(x,"company","company_name","companyName")||"Unknown company"),location=String(value(x,"location","jobGeo","candidate_required_location")||"Remote"),published=dateOrNow(value(x,"publishedAt","pubDate","publication_date","created_at","updated_at")),updated=dateOrNow(value(x,"updatedAt","updated_at","pubDate","publication_date","created_at")||published),url=String(value(x,"url","jobUrl","applyUrl","applicationLink","absolute_url")||""),fingerprint=stableFingerprint({title,company,location,applyUrl:url}),min=Number(value(x,"salaryMin","annualSalaryMin","salary_min","minSalary")||0)||undefined,max=Number(value(x,"salaryMax","annualSalaryMax","salary_max","maxSalary")||0)||undefined,currency=String(value(x,"salaryCurrency","salaryCurrencyCode","currency")||""),salaryText=String(value(x,"salary","salary_text")||(min||max?[min,max].filter(Boolean).map(v=>Number(v).toLocaleString("en-IN")).join("–")+(currency?" "+currency:""):"Not disclosed")),ts=Date.parse(published);
return{id:fingerprint,fingerprint,slug:slug(title+"-"+company)+"-"+fingerprint,title,company,description:description.slice(0,12000),location,workMode:inferMode(location,title,description),type:inferType(title),salary:salaryText,salaryMin:min,salaryMax:max,currency,skills:[...(Array.isArray(x?.tags)?x.tags:[]),...(Array.isArray(x?.skills)?x.skills:[]),...(Array.isArray(x?.keywords)?x.keywords:[])].map(String).filter(Boolean).slice(0,25),category:Array.isArray(x?.category)?String(x.category[0]||"Other"):String(x?.category||x?.jobIndustry||"Other"),experience:inferExperience(title,description,String(x?.jobLevel||x?.experience||x?.seniority||"")),publishedAt:published,updatedAt:updated,sourceName,sourceKind,sourceUrl:url,applyUrl:url,verified:true,freshness:Date.now()-ts<86400000?"today":Date.now()-ts<604800000?"this-week":"older",tags:[],raw:{}}}
async function get(url,headers={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(url,{headers:{"user-agent":"RolePilotBot/2.1 (+https://job-news-prod.onrender.com)",...headers},signal:controller.signal});if(!r.ok)throw new Error(url+" "+r.status);return r}finally{clearTimeout(timer)}}
async function json(url,headers={}){return(await get(url,headers)).json()}async function text(url){return(await get(url)).text()}
function xmlItems(xml){return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1])}function xmlTag(s,tag){const m=s.match(new RegExp("<"+tag+"[^>]*>([\\s\\S]*?)<\/"+tag+">","i"));return m?strip(m[1].replace(/<!\[CDATA\[|\]\]>/g,"")):""}
async function collect(src){if(src.kind==="remotive"){const j=await json(src.url);return(j.jobs||[]).map(x=>common(x,src.name,src.kind))}if(src.kind==="arbeitnow"){const j=await json(src.url);return(j.data||[]).map(x=>common(x,src.name,src.kind))}if(src.kind==="jobicy"){const j=await json(src.url);return(j.jobs||[]).map(x=>common(x,src.name,src.kind))}if(src.kind==="remoteok"){const j=await json(src.url);return j.filter(x=>x?.position).map(x=>common({title:x.position,company:x.company,description:x.description,location:x.location,url:x.url,tags:x.tags,salaryMin:x.salary_min,salaryMax:x.salary_max},src.name,src.kind))}if(src.kind==="himalayas"){let cursor="",out=[];for(let i=0;i<5;i++){const u=src.url+"?limit=20"+(cursor?"&cursor="+encodeURIComponent(cursor):"");const j=await json(u);out.push(...(j.jobs||[]));cursor=j.nextCursor||"";if(!cursor)break}return out.map(x=>common({title:x.title,companyName:x.companyName,description:x.description,location:(x.locationRestrictions||[]).join(", ")||"Remote",minSalary:x.minSalary,maxSalary:x.maxSalary,currency:x.currency,pubDate:x.pubDate,applicationLink:x.applicationLink,tags:x.parentCategories,category:x.category},src.name,src.kind))}if(src.kind==="rss"){const xml=await text(src.url);return xmlItems(xml).map(item=>common({title:xmlTag(item,"title"),description:xmlTag(item,"description"),location:xmlTag(item,"category"),company:xmlTag(item,"author")||src.name,pubDate:xmlTag(item,"pubDate"),url:xmlTag(item,"link")},src.name,src.kind))}if(src.kind==="greenhouse"){const j=await json("https://boards-api.greenhouse.io/v1/boards/"+src.board+"/jobs?content=true");return(j.jobs||[]).map(x=>common({title:x.title,company:companyFromBoard(src.board),description:x.content,location:x.location?.name,url:x.absolute_url,updated_at:x.updated_at,category:x.departments?.map(d=>d.name).join(", ")},src.name,src.kind))}if(src.kind==="lever"){const j=await json("https://api.lever.co/v0/postings/"+src.site+"?mode=json");return(j||[]).map(x=>common({title:x.text,description:x.descriptionPlain||x.description,location:x.categories?.location||"Remote",url:x.hostedUrl,updated_at:x.createdAt},src.name,src.kind))}if(src.kind==="ashby"){const j=await json("https://api.ashbyhq.com/posting-api/job-board/"+src.board+"?includeCompensation=true");return(j.jobs||[]).map(x=>common({title:x.title,description:x.descriptionHtml,location:x.location,url:x.jobUrl,publishedAt:x.publishedAt,category:x.department},src.name,src.kind))}return[]}
async function upsertJson(table,columns,types,rows,updates){if(!db||!rows.length)return;const recordDef=columns.map((c,i)=>c+" "+types[i]).join(",");const selectCols=columns.join(",");const updateSql=updates.map(c=>c+"=EXCLUDED."+c).join(",");const sql="INSERT INTO public."+table+" ("+selectCols+") SELECT "+selectCols+" FROM jsonb_to_recordset($1::jsonb) AS x("+recordDef+") ON CONFLICT DO NOTHING";await db.query(sql,[JSON.stringify(rows)]);if(updates.length&&updates[0]){const json=JSON.stringify(rows);const conflictSql="INSERT INTO public."+table+" ("+selectCols+") SELECT "+selectCols+" FROM jsonb_to_recordset($1::jsonb) AS x("+recordDef+") ON CONFLICT ("+(table==="companies"?"slug":table==="sources"?"id":"id")+") DO UPDATE SET "+updateSql;await db.query(conflictSql,[json])}}
const envTargets=[];for(const board of(process.env.GREENHOUSE_BOARDS||"").split(",").map(s=>s.trim()).filter(Boolean))envTargets.push({id:"greenhouse:"+board,name:"Greenhouse · "+board,kind:"greenhouse",board,url:"https://boards-api.greenhouse.io/v1/boards/"+board+"/jobs",enabled:true});for(const site of(process.env.LEVER_SITES||"").split(",").map(s=>s.trim()).filter(Boolean))envTargets.push({id:"lever:"+site,name:"Lever · "+site,kind:"lever",site,url:"https://api.lever.co/v0/postings/"+site,enabled:true});for(const board of(process.env.ASHBY_BOARDS||"").split(",").map(s=>s.trim()).filter(Boolean))envTargets.push({id:"ashby:"+board,name:"Ashby · "+board,kind:"ashby",board,url:"https://api.ashbyhq.com/posting-api/job-board/"+board,enabled:true});
const SOURCES=[...baseSources,...atsSources,...envTargets],previousRaw=JSON.parse(await fs.readFile(OUT,"utf8").catch(()=>"[]")),previous=previousRaw.filter(j=>j.sourceKind!=="ai_web_discovery"),webDiscovered=JSON.parse(await fs.readFile("data/web-discovered-jobs.json","utf8").catch(()=>"[]")),byId=new Map(previous.map(j=>[j.id,j]));for(const j of webDiscovered)byId.set(j.id,{...(byId.get(j.id)||{}),...j});let totalSeen=0;const stats=[];
const sourceResults=await Promise.all(SOURCES.filter(s=>s.enabled).map(async src=>{
  try{
    const all=await collect(src),maxJobs=Number(src.maxJobs||0),list=maxJobs>0?all.slice(0,maxJobs):all;
    console.log(src.id,list.length);
    return {src,list,ok:true,count:list.length};
  }catch(e){
    const error=e?.message||String(e);
    console.error("source failed",src.id,error);
    return {src,list:[],ok:false,count:0,error};
  }
}));
for(const result of sourceResults){
  const {src,list,ok,count,error}=result;
  totalSeen+=count;
  for(const j of list)byId.set(j.id,{...(byId.get(j.id)||{}),...j});
  stats.push({id:src.id,ok,count,error});
}
function ensureFingerprint(j){const title=String(j?.title||"Opportunity"),company=String(j?.company||"Unknown company"),location=String(j?.location||"Remote"),fingerprint=stableFingerprint({title,company,location,applyUrl:j?.applyUrl||j?.sourceUrl});return{...j,id:String(j?.id||fingerprint),fingerprint,slug:String(j?.slug||(`${slug(title+"-"+company)}-${fingerprint}`))}}
const normalized=[...byId.values()].map(ensureFingerprint),deduped=dedupeJobs(normalized),cutoff=Date.now()-60*24*60*60*1000,jobs=deduped.filter(j=>Date.parse(j.publishedAt||j.updatedAt)>=cutoff&&j.applyUrl&&retainOpportunity(j)).sort((a,b)=>{const ai=isIndiaJob(a)?1:0,bi=isIndiaJob(b)?1:0,af=a.experience==="fresher"||a.type==="internship"?1:0,bf=b.experience==="fresher"||b.type==="internship"?1:0;return (bi-ai)||(bf-af)||(Date.parse(b.publishedAt||b.updatedAt)-Date.parse(a.publishedAt||a.updatedAt));});await fs.writeFile(OUT,JSON.stringify(jobs,null,2)+"\n");
let runId=null;
if(db){
await db.query("UPDATE public.ingest_runs SET status='failed',finished_at=now(),error='Superseded by a newer ingestion run' WHERE status='running' AND started_at < now()-interval '10 minutes'");
const runRows=await db.query("INSERT INTO public.ingest_runs(sources_total) VALUES($1) RETURNING id",[SOURCES.length]);runId=runRows[0]?.id;
const sourceRows=SOURCES.map(s=>({id:s.id,name:s.name,kind:s.kind,url:s.url,enabled:s.enabled!==false,attribution:s.attribution||s.name}));await upsertJson("sources",["id","name","kind","url","enabled","attribution"],["text","text","text","text","boolean","text"],sourceRows,["name","kind","url","enabled","attribution"]);
await db.query("UPDATE public.sources SET enabled=false,updated_at=now() WHERE id <> ALL($1::text[])",[SOURCES.map(s=>s.id)]);
const companyMap=new Map();for(const j of jobs){const s=slug(j.company);if(!companyMap.has(s))companyMap.set(s,{slug:s,name:j.company,source_names:[j.sourceName],last_seen_at:now})}const companyRows=[...companyMap.values()];for(let i=0;i<companyRows.length;i+=250){const chunk=companyRows.slice(i,i+250);const recordDef="slug text,name text,source_names text[],last_seen_at timestamptz";const q="INSERT INTO public.companies(slug,name,source_names,last_seen_at) SELECT slug,name,source_names,last_seen_at FROM jsonb_to_recordset($1::jsonb) AS x("+recordDef+") ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,source_names=EXCLUDED.source_names,last_seen_at=EXCLUDED.last_seen_at RETURNING id,slug";const returned=await db.query(q,[JSON.stringify(chunk)]);for(const c of returned)companyMap.get(c.slug).id=c.id}
const jobRows=jobs.map(j=>{const fingerprint=String(j?.fingerprint||"").trim()||hash([String(j?.title||"Opportunity").toLowerCase(),String(j?.company||"Unknown company").toLowerCase(),String(j?.location||"Remote").toLowerCase()].join("|"));return{id:String(j?.id||fingerprint),fingerprint,slug:String(j?.slug||(`${slug(String(j?.title||"Opportunity")+"-"+String(j?.company||"Unknown company"))}-${fingerprint}`)),title:j.title,company_id:companyMap.get(slug(j.company))?.id||null,company_name:j.company,description:j.description,location:j.location,work_mode:j.workMode,employment_type:j.type,salary_text:j.salary,salary_min:j.salaryMin||null,salary_max:j.salaryMax||null,currency:j.currency||null,skills:j.skills,category:j.category,experience:j.experience,published_at:j.publishedAt,updated_at:j.updatedAt,source_name:j.sourceName,source_url:j.sourceUrl,apply_url:j.applyUrl,verified:true,freshness:j.freshness,tags:j.tags,raw:{},status:"active",last_seen_at:now};});const jobCols=["id","fingerprint","slug","title","company_id","company_name","description","location","work_mode","employment_type","salary_text","salary_min","salary_max","currency","skills","category","experience","published_at","updated_at","source_name","source_url","apply_url","verified","freshness","tags","raw","status","last_seen_at"];const jobTypes=["text","text","text","text","uuid","text","text","text","text","text","text","numeric","numeric","text","text[]","text","text","timestamptz","timestamptz","text","text","text","boolean","text","text[]","jsonb","text","timestamptz"];const mutableCols=jobCols.filter(c=>!["id","fingerprint","last_seen_at"].includes(c));const compareCols=["title","company_id","company_name","description","location","work_mode","employment_type","salary_text","salary_min","salary_max","currency","skills","category","experience","published_at","updated_at","source_name","source_url","apply_url","verified","freshness","tags","raw","status"];for(let i=0;i<jobRows.length;i+=250){const chunk=jobRows.slice(i,i+250),defs=jobCols.map((c,k)=>c+" "+jobTypes[k]).join(","),cols=jobCols.join(","),upd=mutableCols.map(c=>c+"=EXCLUDED."+c).join(","),where="ROW("+compareCols.map(c=>"j."+c).join(",")+") IS DISTINCT FROM ROW("+compareCols.map(c=>"EXCLUDED."+c).join(",")+")",q="INSERT INTO public.jobs AS j ("+cols+") SELECT "+cols+" FROM jsonb_to_recordset($1::jsonb) AS x("+defs+") ON CONFLICT(id) DO UPDATE SET "+upd+" WHERE "+where+" RETURNING id";await db.query(q,[JSON.stringify(chunk)])}
await db.query("UPDATE public.jobs SET status='inactive',updated_at=now() WHERE status='active' AND id <> ALL($1::text[])",[jobs.map(j=>j.id)]);

const links=jobs.map(j=>({job_id:j.id,source_id:SOURCES.find(s=>s.name===j.sourceName)?.id||j.sourceName,source_job_id:j.id,source_url:j.sourceUrl,last_seen_at:now,raw:{}}));for(let i=0;i<links.length;i+=500){const chunk=links.slice(i,i+500),defs="job_id text,source_id text,source_job_id text,source_url text,last_seen_at timestamptz,raw jsonb",q="INSERT INTO public.job_sources(job_id,source_id,source_job_id,source_url,last_seen_at,raw) SELECT job_id,source_id,source_job_id,source_url,last_seen_at,raw FROM jsonb_to_recordset($1::jsonb) AS x("+defs+") ON CONFLICT(job_id,source_id) DO UPDATE SET source_job_id=EXCLUDED.source_job_id,source_url=EXCLUDED.source_url WHERE public.job_sources.source_job_id IS DISTINCT FROM EXCLUDED.source_job_id OR public.job_sources.source_url IS DISTINCT FROM EXCLUDED.source_url";await db.query(q,[JSON.stringify(chunk)])}
for(const s of stats){await db.query("UPDATE public.sources SET last_success_at=$1,last_error=$2,last_count=$3,updated_at=now() WHERE id=$4",[s.ok?new Date().toISOString():null,s.ok?null:s.error,s.count,s.id])}
if(runId)await db.query("UPDATE public.ingest_runs SET finished_at=now(),status=$1,sources_succeeded=$2,jobs_seen=$3,jobs_upserted=$4,metadata=$5::jsonb WHERE id=$6",[stats.some(s=>!s.ok)?"partial":"success",stats.filter(s=>s.ok).length,totalSeen,jobs.length,JSON.stringify({stats}),runId])}
console.log("RolePilot ingestion:",jobs.length,"active opportunities across",SOURCES.length,"source definitions");