import fs from "node:fs/promises";import crypto from "node:crypto";import {neon} from "@neondatabase/serverless";
const baseSources=JSON.parse(await fs.readFile("data/sources.json","utf8")),now=new Date().toISOString(),OUT="data/jobs.json",db=process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null;
const strip=(s="")=>String(s).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g," ").trim();
const slug=s=>String(s).toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90),hash=s=>crypto.createHash("sha1").update(s).digest("hex").slice(0,14);
const value=(x,...keys)=>{for(const k of keys){if(x?.[k]!==undefined&&x?.[k]!==null&&x?.[k]!=="")return x[k]}};
function inferType(t){if(/intern|internship|graduate intern/i.test(t))return"internship";if(/fellow/i.test(t))return"fellowship";if(/contract/i.test(t))return"contract";if(/part[- ]time/i.test(t))return"part-time";if(/full[- ]time/i.test(t))return"full-time";return"other"}
function inferMode(location,title,desc=""){const s=(location+" "+title+" "+desc).toLowerCase();if(/remote|work from home|distributed|worldwide/.test(s))return"remote";if(/hybrid/.test(s))return"hybrid";if(/on[- ]site|onsite|in office/.test(s))return"onsite";return"unknown"}
function dateOrNow(v){try{const d=typeof v==="number"?new Date(v*1000):new Date(v);return Number.isNaN(d.getTime())?now:d.toISOString()}catch{return now}}
function common(x,sourceName,sourceKind){const description=strip(value(x,"description","jobDescription","content","excerpt")||""),title=String(value(x,"title","jobTitle")||"Opportunity"),company=String(value(x,"company","company_name","companyName")||"Unknown company"),location=String(value(x,"location","jobGeo","candidate_required_location")||"Remote"),published=dateOrNow(value(x,"publishedAt","pubDate","publication_date","created_at","updated_at")),updated=dateOrNow(value(x,"updatedAt","updated_at","pubDate","publication_date","created_at")||published),url=String(value(x,"url","jobUrl","applyUrl","applicationLink","absolute_url")||""),fingerprint=hash([title.toLowerCase(),company.toLowerCase(),location.toLowerCase()].join("|")),min=Number(value(x,"salaryMin","annualSalaryMin","salary_min","minSalary")||0)||undefined,max=Number(value(x,"salaryMax","annualSalaryMax","salary_max","maxSalary")||0)||undefined,currency=String(value(x,"salaryCurrency","salaryCurrencyCode","currency")||""),salaryText=String(value(x,"salary","salary_text")||(min||max?[min,max].filter(Boolean).map(v=>Number(v).toLocaleString("en-IN")).join("–")+(currency?" "+currency:""):"Not disclosed")),ts=Date.parse(published);
return{id:fingerprint,fingerprint,slug:slug(title+"-"+company)+"-"+fingerprint,title,company,description:description.slice(0,18000),location,workMode:inferMode(location,title,description),type:inferType(title),salary:salaryText,salaryMin:min,salaryMax:max,currency,skills:[...(Array.isArray(x?.tags)?x.tags:[]),...(Array.isArray(x?.skills)?x.skills:[]),...(Array.isArray(x?.keywords)?x.keywords:[])].map(String).filter(Boolean).slice(0,25),category:Array.isArray(x?.category)?String(x.category[0]||"Other"):String(x?.category||x?.jobIndustry||"Other"),experience:String(x?.jobLevel||x?.experience||x?.seniority||"Not specified"),publishedAt:published,updatedAt:updated,sourceName,sourceKind,sourceUrl:url,applyUrl:url,verified:true,freshness:Date.now()-ts<86400000?"today":Date.now()-ts<604800000?"this-week":"older",tags:[],raw:x}}
async function get(url,headers={}){const r=await fetch(url,{headers:{"user-agent":"JobNewsBot/2.1 (+https://job-news-prod.onrender.com)",...headers}});if(!r.ok)throw new Error(url+" "+r.status);return r}
async function json(url,headers={}){return(await get(url,headers)).json()}async function text(url){return(await get(url)).text()}
function xmlItems(xml){return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1])}function xmlTag(s,tag){const m=s.match(new RegExp("<"+tag+"[^>]*>([\\s\\S]*?)<\/"+tag+">","i"));return m?strip(m[1].replace(/<!\[CDATA\[|\]\]>/g,"")):""}
async function collect(src){if(src.kind==="remotive"){const j=await json(src.url);return(j.jobs||[]).map(x=>common(x,src.name,src.kind))}if(src.kind==="arbeitnow"){const j=await json(src.url);return(j.data||[]).map(x=>common(x,src.name,src.kind))}if(src.kind==="jobicy"){const j=await json(src.url);return(j.jobs||[]).map(x=>common(x,src.name,src.kind))}if(src.kind==="remoteok"){const j=await json(src.url);return j.filter(x=>x?.position).map(x=>common({title:x.position,company:x.company,description:x.description,location:x.location,url:x.url,tags:x.tags,salaryMin:x.salary_min,salaryMax:x.salary_max},src.name,src.kind))}if(src.kind==="himalayas"){let cursor="",out=[];for(let i=0;i<5;i++){const u=src.url+"?limit=20"+(cursor?"&cursor="+encodeURIComponent(cursor):"");const j=await json(u);out.push(...(j.jobs||[]));cursor=j.nextCursor||"";if(!cursor)break}return out.map(x=>common({title:x.title,companyName:x.companyName,description:x.description,location:(x.locationRestrictions||[]).join(", ")||"Remote",minSalary:x.minSalary,maxSalary:x.maxSalary,currency:x.currency,pubDate:x.pubDate,applicationLink:x.applicationLink,tags:x.parentCategories,category:x.category},src.name,src.kind))}if(src.kind==="rss"){const xml=await text(src.url);return xmlItems(xml).map(item=>common({title:xmlTag(item,"title"),description:xmlTag(item,"description"),location:xmlTag(item,"category"),company:xmlTag(item,"author")||src.name,pubDate:xmlTag(item,"pubDate"),url:xmlTag(item,"link")},src.name,src.kind))}if(src.kind==="greenhouse"){const j=await json("https://boards-api.greenhouse.io/v1/boards/"+src.board+"/jobs?content=true");return(j.jobs||[]).map(x=>common({title:x.title,description:x.content,location:x.location?.name,url:x.absolute_url,updated_at:x.updated_at},src.name,src.kind))}if(src.kind==="lever"){const j=await json("https://api.lever.co/v0/postings/"+src.site+"?mode=json");return(j||[]).map(x=>common({title:x.text,description:x.descriptionPlain||x.description,location:x.categories?.location||"Remote",url:x.hostedUrl,updated_at:x.createdAt},src.name,src.kind))}if(src.kind==="ashby"){const j=await json("https://api.ashbyhq.com/posting-api/job-board/"+src.board+"?includeCompensation=true");return(j.jobs||[]).map(x=>common({title:x.title,description:x.descriptionHtml,location:x.location,url:x.jobUrl,publishedAt:x.publishedAt,category:x.department},src.name,src.kind))}return[]}
async function upsertJson(table,columns,types,rows,updates){if(!db||!rows.length)return;const recordDef=columns.map((c,i)=>c+" "+types[i]).join(",");const selectCols=columns.join(",");const updateSql=updates.map(c=>c+"=EXCLUDED."+c).join(",");const sql="INSERT INTO public."+table+" ("+selectCols+") SELECT "+selectCols+" FROM jsonb_to_recordset($1::jsonb) AS x("+recordDef+") ON CONFLICT DO NOTHING";await db.query(sql,[JSON.stringify(rows)]);if(updates.length&&updates[0]){const json=JSON.stringify(rows);const conflictSql="INSERT INTO public."+table+" ("+selectCols+") SELECT "+selectCols+" FROM jsonb_to_recordset($1::jsonb) AS x("+recordDef+") ON CONFLICT ("+(table==="companies"?"slug":table==="sources"?"id":"id")+") DO UPDATE SET "+updateSql;await db.query(conflictSql,[json])}}
const envTargets=[];for(const board of(process.env.GREENHOUSE_BOARDS||"").split(",").map(s=>s.trim()).filter(Boolean))envTargets.push({id:"greenhouse:"+board,name:"Greenhouse · "+board,kind:"greenhouse",board,url:"https://boards-api.greenhouse.io/v1/boards/"+board+"/jobs",enabled:true});for(const site of(process.env.LEVER_SITES||"").split(",").map(s=>s.trim()).filter(Boolean))envTargets.push({id:"lever:"+site,name:"Lever · "+site,kind:"lever",site,url:"https://api.lever.co/v0/postings/"+site,enabled:true});for(const board of(process.env.ASHBY_BOARDS||"").split(",").map(s=>s.trim()).filter(Boolean))envTargets.push({id:"ashby:"+board,name:"Ashby · "+board,kind:"ashby",board,url:"https://api.ashbyhq.com/posting-api/job-board/"+board,enabled:true});
const SOURCES=[...baseSources,...envTargets],previous=JSON.parse(await fs.readFile(OUT,"utf8").catch(()=>"[ ]")),byId=new Map(previous.map(j=>[j.id,j]));let totalSeen=0;const stats=[];
for(const src of SOURCES.filter(s=>s.enabled)){try{const list=await collect(src);totalSeen+=list.length;for(const j of list)byId.set(j.id,{...(byId.get(j.id)||{}),...j});stats.push({id:src.id,ok:true,count:list.length});console.log(src.id,list.length)}catch(e){stats.push({id:src.id,ok:false,count:0,error:e?.message||String(e)});console.error("source failed",src.id,e?.message||String(e))}}
const cutoff=Date.now()-60*24*60*60*1000,jobs=[...byId.values()].filter(j=>Date.parse(j.publishedAt||j.updatedAt)>=cutoff&&j.applyUrl).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,5000);await fs.writeFile(OUT,JSON.stringify(jobs,null,2)+"\n");
let runId=null;
if(db){const runRows=await db.query("INSERT INTO public.ingest_runs(sources_total) VALUES($1) RETURNING id",[SOURCES.length]);runId=runRows[0]?.id;
const sourceRows=SOURCES.map(s=>({id:s.id,name:s.name,kind:s.kind,url:s.url,enabled:s.enabled!==false,attribution:s.attribution||s.name}));await upsertJson("sources",["id","name","kind","url","enabled","attribution"],["text","text","text","text","boolean","text"],sourceRows,["name","kind","url","enabled","attribution"]);
const companyMap=new Map();for(const j of jobs){const s=slug(j.company);if(!companyMap.has(s))companyMap.set(s,{slug:s,name:j.company,source_names:[j.sourceName],last_seen_at:now})}const companyRows=[...companyMap.values()];for(let i=0;i<companyRows.length;i+=250){const chunk=companyRows.slice(i,i+250);const recordDef="slug text,name text,source_names text[],last_seen_at timestamptz";const q="INSERT INTO public.companies(slug,name,source_names,last_seen_at) SELECT slug,name,source_names,last_seen_at FROM jsonb_to_recordset($1::jsonb) AS x("+recordDef+") ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,source_names=EXCLUDED.source_names,last_seen_at=EXCLUDED.last_seen_at RETURNING id,slug";const returned=await db.query(q,[JSON.stringify(chunk)]);for(const c of returned)companyMap.get(c.slug).id=c.id}
const jobRows=jobs.map(j=>({id:j.id,fingerprint:j.fingerprint,slug:j.slug,title:j.title,company_id:companyMap.get(slug(j.company))?.id||null,company_name:j.company,description:j.description,location:j.location,work_mode:j.workMode,employment_type:j.type,salary_text:j.salary,salary_min:j.salaryMin||null,salary_max:j.salaryMax||null,currency:j.currency||null,skills:j.skills,category:j.category,experience:j.experience,published_at:j.publishedAt,updated_at:j.updatedAt,source_name:j.sourceName,source_url:j.sourceUrl,apply_url:j.applyUrl,verified:true,freshness:j.freshness,tags:j.tags,raw:j.raw||{},status:"active",last_seen_at:now}));const jobCols=["id","fingerprint","slug","title","company_id","company_name","description","location","work_mode","employment_type","salary_text","salary_min","salary_max","currency","skills","category","experience","published_at","updated_at","source_name","source_url","apply_url","verified","freshness","tags","raw","status","last_seen_at"];const jobTypes=["text","text","text","text","uuid","text","text","text","text","text","text","numeric","numeric","text","text[]","text","text","timestamptz","timestamptz","text","text","text","boolean","text","text[]","jsonb","text","timestamptz"];for(let i=0;i<jobRows.length;i+=250){const chunk=jobRows.slice(i,i+250),defs=jobCols.map((c,k)=>c+" "+jobTypes[k]).join(","),cols=jobCols.join(","),upd=jobCols.filter(c=>!["id","fingerprint"].includes(c)).map(c=>c+"=EXCLUDED."+c).join(","),q="INSERT INTO public.jobs ("+cols+") SELECT "+cols+" FROM jsonb_to_recordset($1::jsonb) AS x("+defs+") ON CONFLICT(id) DO UPDATE SET "+upd;await db.query(q,[JSON.stringify(chunk)])}
await db.query("UPDATE public.jobs SET search_document=to_tsvector('english',coalesce(title,'')||' '||coalesce(company_name,'')||' '||coalesce(description,'')||' '||coalesce(location,'')||' '||coalesce(category,'')||' '||coalesce(experience,'')||' '||coalesce(array_to_string(skills,' '),''),updated_at=updated_at) WHERE id=ANY($1::text[])",[jobs.map(j=>j.id)]);
const links=jobs.map(j=>({job_id:j.id,source_id:SOURCES.find(s=>s.name===j.sourceName)?.id||j.sourceName,source_job_id:j.id,source_url:j.sourceUrl,last_seen_at:now,raw:j.raw||{}}));for(let i=0;i<links.length;i+=500){const chunk=links.slice(i,i+500),defs="job_id text,source_id text,source_job_id text,source_url text,last_seen_at timestamptz,raw jsonb",q="INSERT INTO public.job_sources(job_id,source_id,source_job_id,source_url,last_seen_at,raw) SELECT job_id,source_id,source_job_id,source_url,last_seen_at,raw FROM jsonb_to_recordset($1::jsonb) AS x("+defs+") ON CONFLICT(job_id,source_id) DO UPDATE SET source_job_id=EXCLUDED.source_job_id,source_url=EXCLUDED.source_url,last_seen_at=EXCLUDED.last_seen_at,raw=EXCLUDED.raw";await db.query(q,[JSON.stringify(chunk)])}
for(const s of stats){await db.query("UPDATE public.sources SET last_success_at=$1,last_error=$2,last_count=$3,updated_at=now() WHERE id=$4",[s.ok?new Date().toISOString():null,s.ok?null:s.error,s.count,s.id])}
if(runId)await db.query("UPDATE public.ingest_runs SET finished_at=now(),status=$1,sources_succeeded=$2,jobs_seen=$3,jobs_upserted=$4,metadata=$5::jsonb WHERE id=$6",[stats.some(s=>!s.ok)?"partial":"success",stats.filter(s=>s.ok).length,totalSeen,jobs.length,JSON.stringify({stats}),runId])}
console.log("JobNews ingestion:",jobs.length,"active jobs across",SOURCES.length,"source definitions");